name: issue_creation

on:
  workflow_dispatch
    
jobs:
  issue_job:
    runs-on: ubuntu-latest
    steps:
      - name: Create issues
        uses: gofair-foundation/qualification-issue-creation@v1
        
