name: issue_creation

on:
  schedule:
    - cron: '30 4 * * SUN'
  workflow_dispatch:
    
jobs:
  issue_job:
    runs-on: ubuntu-latest
    steps:
      - name: Create issues
        uses: gofair-foundation/qualification-issue-creation-action@v0.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
